"""add null constraint to booking type table

Revision ID: a8d1f055ee70
Revises: 2f8a18ec7d08
Create Date: 2023-09-30 13:47:12.690976+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a8d1f055ee70"
down_revision: Union[str, None] = "2f8a18ec7d08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("booking", sa.Column("user_id", sa.Integer(), nullable=False))
    op.drop_constraint("booking_user_fkey", "booking", type_="foreignkey")
    op.create_foreign_key(None, "booking", "user", ["user_id"], ["id"])
    op.drop_column("booking", "user")
    op.alter_column(
        "booking_type", "description", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "booking_type", "description", existing_type=sa.VARCHAR(), nullable=False
    )
    op.add_column(
        "booking", sa.Column("user", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "booking", type_="foreignkey")
    op.create_foreign_key("booking_user_fkey", "booking", "user", ["user"], ["id"])
    op.drop_column("booking", "user_id")
    # ### end Alembic commands ###
