"""add first name to profile table

Revision ID: d935d0c97b7e
Revises: db78b0bb0a70
Create Date: 2023-09-26 14:17:27.598736+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d935d0c97b7e"
down_revision: Union[str, None] = "db78b0bb0a70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("profile", sa.Column("first_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profile", "first_name")
    # ### end Alembic commands ###
