"""create profile table

Revision ID: db78b0bb0a70
Revises: 3158bb94ae81
Create Date: 2023-09-21 22:35:43.689300+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "db78b0bb0a70"
down_revision: Union[str, None] = "3158bb94ae81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("telegram", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("user", sa.Column("is_admin", sa.Boolean(), nullable=False))
    op.drop_column("user", "telegram")
    op.drop_column("user", "phone")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("phone", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "user", sa.Column("telegram", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("user", "is_admin")
    op.drop_table("profile")
    # ### end Alembic commands ###
