version: '3.9'

services:
  db:
    container_name: database
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT-5432}:5432

volumes:
  postgres_data:
