version: '3.9'

services:
  db:
    container_name: database
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT-5432}:5432

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - ${REDIS_PORT-6397}:6397

  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./app:/app
    env_file: .env
    ports:
      - ${SERVER_PORT-8000}:${EXTERNAL_PORT-8000}
    entrypoint: ["/code/entrypoint.sh"]
    depends_on:
      - db
      - redis

  worker:
    container_name: celery-worker
    build: .
    command: poetry run celery -A src.config.worker worker -l INFO
    env_file:
      .env
    depends_on:
      - app
      - redis

volumes:
  postgres_data:
